<a href="https://colab.research.google.com/github/VladousSparrowous/HSE-homeworks/blob/main/python_HW1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# @title A

def bits_seqs(n):

    current_seq = -1

    count_seq_0 = 0
    count_seq_1 = 0

    while n != 0 and n != n // 2:
        k = n % 2
        if k != current_seq:

            if k == 1 and current_seq != -1:
                count_seq_0 += 1

            if k == 0 and current_seq != -1:
                count_seq_1 += 1

            current_seq = k
        n = n // 2

    if n == 0:
        return count_seq_0
    else:
        return count_seq_1

print(bits_seqs(100))

2


In [ ]:
# @title B

def invert_digits(n):
    answ = 0
    miss = 0
    while n:
        k = n % 10
        answ = 10 * answ + k
        if answ == 0:
            miss += 1
        n = n // 10

    if miss:
        return answ, miss

    return answ

print(invert_digits(1234567890))

(987654321, 1)


In [2]:
# @title C

def pr(ba):
    print(*[i for i in ba])

def ba_dedup(ba):
    n = len(ba)
    ind = 0
    was_duplicat = False

    for i in range(n):
        if ind == 0 or ba[i] != ba[ind - 1]:
            ba[ind] = ba[i]
            ind += 1
        else:
            was_duplicat = True

    if not was_duplicat:
        return None

    ba[ind] = 255
    ind += 1
    i = 0
    while ind < n:
        ba[ind] = ba[i]
        ind += 1
        i += 1
        if ba[i - 1] == 255:
            i = 0


In [3]:
A = bytearray([11, 11, 11, 11, 11, 22, 22, 22, 22, 22, 33, 44, 44, 44, 55])
pr(A)
print(len(A))
ba_dedup(A)
print('------------------------')
pr(A)
print(len(A))

11 11 11 11 11 22 22 22 22 22 33 44 44 44 55
15
------------------------
11 22 33 44 55 255 11 22 33 44 55 255 11 22 33
15


In [182]:
# @title D

def varint_encode(num):
    num = bin(num)[2:]

    bonus_len = len(num) % 7

    if bonus_len:
        bonus_len = 7 - bonus_len

    if bonus_len:
        num = ''.join(['0'] * bonus_len) + num

    last_bit = '1'
    answ = bytearray()

    for i in range(len(num), 6, -7):
        if i-7 == 0:
            last_bit = '0'
        b = last_bit + num[i-7: i]

        answ.append(int(b, 2))
    return answ

In [254]:
ba = varint_encode(256)
pr(ba)

128 2


In [237]:
# @title E

def varint_decode(ba):
    int_array = []
    last_num = 0
    count = 1
    for i in ba:
        if i >= 128:
            delta = i - 128
            last_num += delta * count
            count = count * 128
        else:
            last_num += i * count
            int_array.append(last_num)
            count = 1
            last_num = 0
    if count != 1:
        int_array.append(None)
    return int_array

In [239]:
A = bytearray([172, 2, 2, 128])
print(varint_decode(A))

[300, 2, None]


In [240]:
# @title F

def zigzag_encode(num):
    if num >= 0:
        num = 2 * num
    else:
        num = -2 * num - 1
    num = bin(num)[2:]

    bonus_len = len(num) % 7

    if bonus_len:
        bonus_len = 7 - bonus_len

    if bonus_len:
        num = ''.join(['0'] * bonus_len) + num

    last_bit = '1'
    answ = bytearray()

    for i in range(len(num), 6, -7):
        if i-7 == 0:
            last_bit = '0'
        b = last_bit + num[i-7: i]

        answ.append(int(b, 2))
    return answ

In [241]:
# @title G

def zigzag_decode(ba):
    int_array = []
    last_num = 0
    count = 1
    for i in ba:
        if i >= 128:
            delta = i - 128
            last_num += delta * count
            count = count * 128
        else:
            last_num += i * count
            if last_num % 2:
                last_num = -1 * ((last_num + 1) // 2)
            else:
                last_num = last_num // 2

            int_array.append(last_num)
            count = 1
            last_num = 0

    if count != 1:
        int_array.append(None)
    return int_array

In [243]:
A = bytearray([172, 2, 2, 1, 128])
print(zigzag_decode(A))

[150, 1, -1, None]


In [265]:
# @title H

def is_prime_number(num):
    if isinstance(num, int) and num > 0:
        if num == 1:
            return False

        for i in range(2, int(num**0.5) + 1):
            if num % i == 0:
                return False
        return True
    return None

In [266]:
print(is_prime_number(1))

False


In [70]:
# @title I

def division_steps(a, b):
    s = ''
    start = False
    answ = []
    answ.append(f'{bin(a)[2:]}/{bin(b)[2:]}')
    if a == 0:
        answ.append('0.')
        return answ

    while a:
        if a < b:
            if not start:
                s = '0.'
                start = True
            else:
                s += '0'
            a = a * 2
            answ.append(f'*: {bin(a)[2:]}/{bin(b)[2:]} {s}')
        else:
            s += '1'
            a = (a - b) * 2
            answ.append(f'-: {bin(a)[2:]}/{bin(b)[2:]} {s}')
    answ.append(s)
    return answ

In [71]:
print(*division_steps(15, 24),sep='\n')

1111/11000
*: 11110/11000 0.
-: 1100/11000 0.1
*: 11000/11000 0.10
-: 0/11000 0.101
0.101


In [ ]:
# @title J

def utf8_size_hist(src):
    ...

In [93]:
import numpy as np
A = np.array([[0, 4, -7], [-4, 0, 4], [7, -4, 0]])
v1 = np.array([-4, -7, -4]) / 9
v2 = np.array([-7, 8, -7]) / (9 * np.sqrt(2))
v3 = np.array([1, 0, -1]) / np.sqrt(2)
Q =
P = np.vstack((v1, v2, v3)).T
P_1 = np.linalg.inv(P)
print(P_1 @ A @ P)

[[ 9.86864911e-17  1.22118302e-16 -1.57009246e-16]
 [ 4.03725474e-16  6.63401474e-16 -9.00000000e+00]
 [-4.67521021e-16  9.00000000e+00  1.37549587e-16]]
